/*This website, SoapCalc.net, and its content is copyright of BRL Enterprises, Inc. USA - © BRL Enterprises, Inc. USA 2001-2014. All rights reserved.
Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following:
•	you may print or save to a local hard disk extracts for your personal and non-commercial use only
•	you may copy the content to individual third parties for their personal use, but only if you acknowledge www.SoapCalc.net as the source of the material
You may not, except with our express written permission, distribute or commercially exploit the content.
Nor may you transmit it or store it in any other website or other form of electronic retrieval system.*/
var Hard=0,Cleansing=0,Bubbly=0,Conditioning=0,Creamy=0,Iodine=0,INS=0,Lauric=0,Linoleic=0,Linolenic=0,Myristic=0,Oleic=0,Palmitic=0,Ricinoleic=0,Stearic=0,Saturated=0,MonoUnsaturated=0,PolyUnsaturated=0,ary14RecipeWeightVals=Array(14),ary14RecipeSapVals=Array(14),ary14RecipeSelIndexes=Array(14),ary14RecipePercentVals=Array(14),ary14SelectedOilIds=Array(14),g_tot=0,g_Computed=!1,g_90PercentKOH,unit="lb",FixedConc,FixedRatio;
function Oil(b,a,c,d,g,f,e,k,m,n,p,q,l){this.id=b;this.name=a;this.sap=c;this.iodine=d;this.ins=g;this.lauric=f;this.myristic=e;this.palmitic=k;this.stearic=m;this.ricinoleic=n;this.oleic=p;this.linoleic=q;this.linolenic=l}var aryAllOils=[];aryAllOils.push(new Oil(145,"Abyssinian Oil",.168,98,70,0,0,3,2,0,18,11,4));aryAllOils.push(new Oil(114,"Almond Butter",.188,70,118,0,1,9,15,0,58,16,0));aryAllOils.push(new Oil(1,"Almond Oil, sweet",.195,99,97,0,0,7,0,0,71,18,0));
aryAllOils.push(new Oil(68,"Aloe Butter",.24,9,241,45,18,8,3,0,7,2,0));aryAllOils.push(new Oil(96,"Andiroba Oil,karaba,crabwood",.188,68,120,0,0,28,8,0,51,9,0));aryAllOils.push(new Oil(2,"Apricot Kernal Oil",.195,100,91,0,0,6,0,0,66,27,0));aryAllOils.push(new Oil(58,"Argan Oil",.191,95,95,0,1,14,0,0,46,34,1));aryAllOils.push(new Oil(53,"Avocado butter",.187,67,120,0,0,21,10,0,53,6,2));aryAllOils.push(new Oil(3,"Avocado Oil",.186,86,99,0,0,20,2,0,58,12,0));
aryAllOils.push(new Oil(4,"Babassu Oil",.245,15,230,50,20,11,4,0,10,0,0));aryAllOils.push(new Oil(59,"Baobab Oil",.2,75,125,0,1,24,4,0,37,28,2));aryAllOils.push(new Oil(5,"Beeswax",.094,10,84,0,0,0,0,0,0,0,0));aryAllOils.push(new Oil(6,"Black Cumin Seed Oil, nigella sativa",.195,133,62,0,0,13,3,0,22,60,1));aryAllOils.push(new Oil(136,"Black Current Seed Oil",.19,178,12,0,0,6,2,0,13,46,29));aryAllOils.push(new Oil(66,"Borage Oil",.19,135,55,0,0,10,4,0,20,43,5));
aryAllOils.push(new Oil(146,"Brazil Nut Oil",.19,100,90,0,0,13,11,0,39,36,0));aryAllOils.push(new Oil(138,"Broccoli Seed Oil, Brassica Oleracea",.172,105,67,0,0,3,1,0,14,11,9));aryAllOils.push(new Oil(147,"Buriti Oil",.223,70,153,0,0,17,2,0,71,7,1));aryAllOils.push(new Oil(60,"Camelina Seed Oil",.188,144,44,0,0,6,2,0,24,19,45));aryAllOils.push(new Oil(80,"Camellia Oil, Tea Seed",.193,78,115,0,0,9,2,0,77,8,0));aryAllOils.push(new Oil(142,"Candelilla Wax",.044,32,12,0,0,0,0,0,0,0,0));
aryAllOils.push(new Oil(7,"Canola Oil",.186,110,56,0,0,4,2,0,61,21,9));aryAllOils.push(new Oil(84,"Canola Oil, high oleic",.186,96,90,0,0,4,2,0,74,12,4));aryAllOils.push(new Oil(144,"Carrot Seed Oil, cold pressed",.144,56,0,0,0,4,0,0,80,13,0));aryAllOils.push(new Oil(8,"Castor Oil",.18,86,95,0,0,0,0,90,4,4,0));aryAllOils.push(new Oil(79,"Cherry Kern1 Oil, p. avium",.19,128,62,0,0,8,3,0,31,45,11));aryAllOils.push(new Oil(90,"Cherry Kern2 Oil, p. cerasus",.192,118,74,0,0,6,3,0,50,40,0));
aryAllOils.push(new Oil(56,"Chicken Fat",.195,69,130,0,1,25,7,0,38,21,0));aryAllOils.push(new Oil(9,"Cocoa Butter",.194,37,157,0,0,28,33,0,35,3,0));aryAllOils.push(new Oil(10,"Coconut Oil, 76 deg",.257,10,258,48,19,9,3,0,8,2,0));aryAllOils.push(new Oil(72,"Coconut Oil, 92 deg",.257,3,258,48,19,9,3,0,8,2,0));aryAllOils.push(new Oil(65,"Coconut Oil, fractionated",.325,1,324,2,1,0,0,0,0,0,0));aryAllOils.push(new Oil(93,"Coffee Bean Oil, green",.185,85,100,0,0,38,8,0,9,39,2));
aryAllOils.push(new Oil(74,"Coffee Bean Oil, roasted",.18,87,93,0,0,40,0,0,8,38,2));aryAllOils.push(new Oil(102,"Cohune Oil",.205,30,175,51,13,8,3,0,18,3,0));aryAllOils.push(new Oil(11,"Corn Oil",.192,117,69,0,0,12,2,0,32,51,1));aryAllOils.push(new Oil(12,"Cottonseed Oil",.194,108,89,0,0,13,13,0,18,52,1));aryAllOils.push(new Oil(92,"Cranberry Seed Oil",.19,150,40,0,0,6,2,0,23,37,32));aryAllOils.push(new Oil(104,"Crisco, new w/palm",.193,111,82,0,0,20,5,0,28,40,6));
aryAllOils.push(new Oil(13,"Crisco, old",.192,93,115,0,0,13,13,0,18,52,0));aryAllOils.push(new Oil(101,"Cupuacu Butter",.192,39,153,0,0,8,35,0,42,2,0));aryAllOils.push(new Oil(87,"Duck Fat, flesh and skin",.194,72,122,0,1,26,9,0,44,13,1));aryAllOils.push(new Oil(14,"Emu Oil",.19,60,128,0,0,23,9,0,47,8,0));aryAllOils.push(new Oil(15,"Evening Primrose Oil",.19,160,30,0,0,0,0,0,0,80,9));aryAllOils.push(new Oil(16,"Flax Oil, linseed",.19,180,-6,0,0,6,3,0,27,13,50));
aryAllOils.push(new Oil(95,"Ghee, any bovine",.227,30,191,4,11,28,12,0,19,2,1));aryAllOils.push(new Oil(17,"Goose Fat",.192,65,130,0,0,21,6,0,54,10,0));aryAllOils.push(new Oil(18,"Grapeseed Oil",.181,131,66,0,0,8,4,0,20,68,0));aryAllOils.push(new Oil(19,"Hazelnut Oil",.195,97,94,0,0,5,3,0,75,10,0));aryAllOils.push(new Oil(20,"Hemp Oil",.193,165,39,0,0,6,2,0,12,57,21));aryAllOils.push(new Oil(94,"Horse Oil",.196,79,117,0,3,26,5,0,10,20,19));
aryAllOils.push(new Oil(62,"Illipe Butter",.185,33,152,0,0,17,45,0,35,0,0));aryAllOils.push(new Oil(143,"Japan Wax",.215,11,204,0,1,80,7,0,4,0,0));aryAllOils.push(new Oil(108,"Jatropha Oil, soapnut seed oil",.193,102,91,0,0,9,7,0,44,34,0));aryAllOils.push(new Oil(21,"Jojoba Oil (a Liquid Wax Ester)",.092,83,11,0,0,0,0,0,12,0,0));aryAllOils.push(new Oil(51,"Karanja Oil",.183,85,98,0,0,6,6,0,58,15,0));aryAllOils.push(new Oil(23,"Kokum Butter",.19,35,155,0,0,4,56,0,36,1,0));
aryAllOils.push(new Oil(86,"Kpangnan Butter",.191,42,149,0,0,6,44,0,49,1,0));aryAllOils.push(new Oil(24,"Kukui nut Oil",.189,168,24,0,0,6,2,0,20,42,29));aryAllOils.push(new Oil(25,"Lanolin liquid Wax",.106,27,83,0,0,0,0,0,0,0,0));aryAllOils.push(new Oil(26,"Lard, Pig Tallow (Manteca)",.198,57,139,0,1,28,13,0,46,6,0));aryAllOils.push(new Oil(127,"Laurel Fruit Oil",.198,74,124,25,1,15,1,0,31,26,1));aryAllOils.push(new Oil(125,"Lauric Acid",.28,0,280,99,1,0,0,0,0,0,0));
aryAllOils.push(new Oil(27,"Linseed Oil, flax",.19,180,-6,0,0,6,3,0,27,13,50));aryAllOils.push(new Oil(119,"Loofa Seed Oil, Luffa cylinderica",.187,108,79,0,0,9,18,0,30,47,0));aryAllOils.push(new Oil(124,"Macadamia Nut Butter",.188,70,118,0,1,6,12,0,56,3,1));aryAllOils.push(new Oil(28,"Macadamia Nut Oil",.195,76,119,0,0,9,5,0,59,2,0));aryAllOils.push(new Oil(141,"Mafura Butter, Trichilia emetica ",.198,66,132,0,1,37,3,0,49,11,1));
aryAllOils.push(new Oil(29,"Mango Seed Butter",.191,45,146,0,0,7,42,0,45,3,0));aryAllOils.push(new Oil(30,"Mango Seed Oil",.19,60,130,0,0,8,27,0,52,8,1));aryAllOils.push(new Oil(99,"Marula Oil",.192,73,119,0,0,11,7,0,75,4,0));aryAllOils.push(new Oil(31,"Meadowfoam Oil",.169,92,77,0,0,0,0,0,0,0,0));aryAllOils.push(new Oil(32,"Milk Fat, any bovine",.227,30,191,4,11,28,12,0,19,2,1));aryAllOils.push(new Oil(130,"Milk Thistle Oil",.196,115,81,0,0,7,2,0,26,64,0));
aryAllOils.push(new Oil(67,"Mink Oil",.196,55,141,0,0,0,0,0,0,0,0));aryAllOils.push(new Oil(69,"Monoi de Tahiti  Oil",.255,9,246,44,16,10,3,0,0,2,0));aryAllOils.push(new Oil(109,"Moringa Oil",.192,68,124,0,0,7,7,0,71,2,0));aryAllOils.push(new Oil(63,"Mowrah Butter",.194,62,132,0,0,24,22,0,36,15,0));aryAllOils.push(new Oil(106,"Murumuru Butter",.275,25,250,47,26,6,3,0,15,3,0));aryAllOils.push(new Oil(103,"Mustard Oil, kachi ghani",.173,101,72,0,0,2,2,0,18,14,9));
aryAllOils.push(new Oil(76,"Myristic Acid",.247,1,246,0,99,0,0,0,0,0,0));aryAllOils.push(new Oil(121,"Neatsfoot Oil",.18,90,90,0,0,0,0,0,0,0,0));aryAllOils.push(new Oil(33,"Neem Seed Oil",.193,72,121,0,2,21,16,0,46,12,0));aryAllOils.push(new Oil(139,"Nutmeg Butter",.1624,46,116,3,83,4,0,0,5,0,0));aryAllOils.push(new Oil(117,"Oat Oil",.19,104,86,0,0,15,2,0,40,39,0));aryAllOils.push(new Oil(88,"Oleic Acid",.202,92,110,0,0,0,0,0,99,0,0));
aryAllOils.push(new Oil(34,"Olive Oil",.19,85,105,0,0,14,3,0,69,12,1));aryAllOils.push(new Oil(52,"Olive Oil  pomace",.188,84,104,0,0,14,3,0,69,12,2));aryAllOils.push(new Oil(82,"Ostrich Oil",.1946,97,128,3,1,26,6,0,37,17,3));aryAllOils.push(new Oil(35,"Palm Kernel Oil",.247,20,227,49,16,8,2,0,15,3,0));aryAllOils.push(new Oil(126,"Palm Kernel Oil Flakes, hydrogenated",.247,20,227,49,17,8,16,0,4,0,0));aryAllOils.push(new Oil(36,"Palm Oil",.199,53,145,0,1,44,5,0,39,10,0));
aryAllOils.push(new Oil(113,"Palm Stearin",.199,48,151,0,2,60,5,0,26,7,0));aryAllOils.push(new Oil(77,"Palmitic Acid",.215,2,213,0,0,98,0,0,0,0,0));aryAllOils.push(new Oil(131,"Palmolein",.2,58,142,0,1,40,5,0,43,11,0));aryAllOils.push(new Oil(120,"Papaya seed oil, Carica papaya",.158,67,91,0,0,13,5,0,76,3,0));aryAllOils.push(new Oil(37,"Passion Fruit Seed Oil",.183,136,47,0,0,10,3,0,15,70,1));aryAllOils.push(new Oil(148,"Pataua (Patawa) Oil",.2,77,123,0,0,13,4,0,78,3,1));
aryAllOils.push(new Oil(70,"Peach Kernel Oil",.191,108,87,0,0,6,2,0,65,25,1));aryAllOils.push(new Oil(38,"Peanut Oil",.192,92,99,0,0,8,3,0,56,26,0));aryAllOils.push(new Oil(137,"Pecan Oil",.19,113,77,0,0,7,2,0,50,39,2));aryAllOils.push(new Oil(75,"Perilla Seed Oil",.19,196,-6,0,0,6,2,0,15,16,56));aryAllOils.push(new Oil(85,"Pine Tar, lye calc only no FA",.06,0,0,0,0,0,0,0,0,0,0));aryAllOils.push(new Oil(39,"Pistachio Oil",.186,95,92,0,0,11,1,0,63,25,0));
aryAllOils.push(new Oil(107,"Plum Kernel Oil",.194,98,96,0,0,3,0,0,68,23,0));aryAllOils.push(new Oil(128,"Pomegranate Seed Oil",.19,22,168,0,0,3,3,0,7,7,78));aryAllOils.push(new Oil(73,"Poppy Seed Oil",.194,140,54,0,0,10,2,0,17,69,2));aryAllOils.push(new Oil(149,"Pracaxi (Pracachy) Seed Oil - hair conditioner",.175,68,107,1,1,2,2,0,44,2,2));aryAllOils.push(new Oil(83,"Pumpkin Seed Oil virgin",.195,128,67,0,0,11,8,0,33,50,0));aryAllOils.push(new Oil(91,"Rabbit Fat",.201,85,116,0,3,30,6,0,30,20,5));
aryAllOils.push(new Oil(40,"Rapeseed Oil, unrefined canola",.175,106,69,0,0,4,1,0,17,13,9));aryAllOils.push(new Oil(129,"Raspberry Seed Oil",.187,163,24,0,0,3,0,0,13,55,26));aryAllOils.push(new Oil(89,"Red Palm Butter",.199,53,145,0,1,44,5,0,39,10,0));aryAllOils.push(new Oil(41,"Rice Bran Oil, refined",.187,100,87,0,1,22,3,0,38,34,2));aryAllOils.push(new Oil(61,"Rosehip Oil",.187,188,10,0,0,4,2,0,12,46,31));
aryAllOils.push(new Oil(122,"Sacha Inchi, Plukenetia volubilis",.188,141,47,0,0,4,3,0,10,35,48));aryAllOils.push(new Oil(42,"Safflower Oil",.192,145,47,0,0,7,0,0,15,75,0));aryAllOils.push(new Oil(78,"Safflower Oil, high oleic",.19,93,97,0,0,5,2,0,77,15,0));aryAllOils.push(new Oil(64,"Sal Butter",.185,39,146,0,0,6,44,0,40,2,0));aryAllOils.push(new Oil(140,"Salmon Oil",.185,169,16,0,5,19,2,0,23,2,1));aryAllOils.push(new Oil(111,"Saw Palmetto Extract",.23,45,185,29,11,8,2,0,35,4,1));
aryAllOils.push(new Oil(110,"Saw Palmetto Oil",.22,44,176,29,13,9,2,0,31,4,1));aryAllOils.push(new Oil(116,"Sea Buckthorn Oil, seed",.195,165,30,0,0,7,3,0,14,36,38));aryAllOils.push(new Oil(115,"Sea Buckthorn Oil, seed and berry",.183,86,97,0,0,30,1,0,28,10,0));aryAllOils.push(new Oil(43,"Sesame Oil",.188,110,81,0,0,10,5,0,40,43,0));aryAllOils.push(new Oil(44,"Shea Butter",.179,59,116,0,0,5,40,0,48,6,0));aryAllOils.push(new Oil(22,"Shea Oil, fractionated",.185,83,102,0,0,6,10,0,73,11,0));
aryAllOils.push(new Oil(133,"SoapQuick, conventional",.212,59,153,13,6,17,3,5,42,8,1));aryAllOils.push(new Oil(134,"SoapQuick, organic",.213,56,156,13,5,20,3,0,45,10,0));aryAllOils.push(new Oil(45,"Soybean Oil",.191,131,61,0,0,11,5,0,24,50,8));aryAllOils.push(new Oil(81,"Soybean, 27.5% hydrogenated",.191,78,113,0,0,9,15,0,41,7,1));aryAllOils.push(new Oil(132,"Soybean, fully hydrogenated (soy wax)",.192,1,191,0,0,11,87,0,0,0,0));aryAllOils.push(new Oil(46,"Stearic Acid",.198,2,196,0,0,0,99,0,0,0,0));
aryAllOils.push(new Oil(47,"Sunflower Oil",.189,133,63,0,0,7,4,0,16,70,1));aryAllOils.push(new Oil(71,"Sunflower Oil, high oleic",.189,83,106,0,0,3,4,0,83,4,1));aryAllOils.push(new Oil(112,"Tallow Bear",.1946,92,100,0,2,7,3,0,70,9,0));aryAllOils.push(new Oil(48,"Tallow Beef",.2,45,147,2,6,28,22,0,36,3,1));aryAllOils.push(new Oil(54,"Tallow Deer",.193,31,166,0,1,20,24,0,30,15,3));aryAllOils.push(new Oil(123,"Tallow Goat",.192,40,152,5,11,23,30,0,29,2,0));
aryAllOils.push(new Oil(55,"Tallow Sheep",.194,54,156,4,10,24,13,0,26,5,0));aryAllOils.push(new Oil(57,"Tamanu Oil, kamani",.208,111,82,0,0,12,13,0,34,38,1));aryAllOils.push(new Oil(97,"Tucuma Seed Butter",.238,13,175,48,23,6,0,0,13,0,0));aryAllOils.push(new Oil(100,"Ucuuba Butter",.205,38,167,0,0,0,31,0,44,5,0));aryAllOils.push(new Oil(105,"Walmart GV Shortening, tallow, palm",.198,49,151,1,4,35,14,0,37,6,1));aryAllOils.push(new Oil(49,"Walnut Oil",.189,145,45,0,0,7,2,0,18,60,0));
aryAllOils.push(new Oil(135,"Watermelon Seed Oil",.19,119,71,0,0,11,10,0,18,60,1));aryAllOils.push(new Oil(50,"Wheat Germ Oil",.183,128,58,0,0,17,2,0,17,58,0));aryAllOils.push(new Oil(98,"Yangu, cape chestnut",.192,95,97,0,0,18,5,0,45,30,1));aryAllOils.push(new Oil(118,"Zapote seed oil, (Aceite de Sapuyul or Mamey)",.188,72,116,0,0,9,21,0,52,13,0));var aryRanges=Array(7),sRangeTrailer="<br /><br /><span style='font-size:12px;font-style:italic'>These ranges for are designed as guidelines. With experience, you may want to venture above or below these limits.</span>";
aryRanges[0]="<span style='font-weight:bold'>Hardness</span> (in the All column): 29 to 54, higher is harder."+sRangeTrailer;aryRanges[1]="<span style='font-weight:bold'>Cleansing</span> (in the All column): 12 to 22, all soap cleanses but the higher numbers more so."+sRangeTrailer;aryRanges[2]="<span style='font-weight:bold'>Conditioning</span> (in the All column): 44 to 69, higher offers more skin conditioning."+sRangeTrailer;
aryRanges[3]="<span style='font-weight:bold'>Bubbly</span> (in the All column): 14 to 46, higher gives a more bubbly lather."+sRangeTrailer;aryRanges[4]="<span style='font-weight:bold'>Creamy</span> (in the All column): 16 to 48, higher gives a more creamy lather."+sRangeTrailer;aryRanges[5]="<span style='font-weight:bold'>Iodine Value</span> (in the All column): 41 to 70, lower equals harder bar, much above 70 and bar could possibly be too soft."+sRangeTrailer;
aryRanges[6]="<span style='font-weight:bold'>INS</span> (in the All column): 136 to 165, the commonly accepted ideal is 160.&nbsp; This value gauges the physical qualities of the bar; primarily hardness, with higher being harder."+sRangeTrailer;var aryFADetail=Array(8),tailFADetail="<br /><br />Click/Tap on green <span style='font-weight:700;font-size:14px;font-family:Courier'>i</span> button to get more detail from Wikipedia.";aryFADetail[0]="<b>Lauric Acid</b><br /><br />&bull; 12:0<br />&bull; Saturated<br />&bull; dodecanoic acid. &nbsp;&nbsp;(doe-dec-a-no-ik)";
aryFADetail[1]="<b>Myristic Acid</b><br /><br />&bull; 14:0<br />&bull; Saturated<br />&bull; tetradecanoic acid. &nbsp;&nbsp;(te-tra-dec-a-no-ik)";aryFADetail[2]="<b>Palmitic Acid</b><br /><br />&bull; 16:0<br />&bull; Saturated<br />&bull; hexadecanoic acid. &nbsp;&nbsp;(hex-a-dec-a-no-ik)";aryFADetail[3]="<b>Stearic Acid</b><br /><br />&bull; 18:0<br />&bull; Saturated<br />&bull; octadecanoic acid. &nbsp;&nbsp;(oc-ta-dec-a-no-ik)";aryFADetail[4]="<b>Ricinoleic Acid</b><br /><br />&bull; 18:1<br />&bull; MonoUnsaturated<br />&bull; 12-hydroxy-9-cis-octadecenoic acid.<br />(hy-drox-y, sis, oc-ta-dec-e-no-ik)";
aryFADetail[5]="<b>Oleic Acid</b><br /><br />&bull; 18:1<br />&bull; MonoUnsaturated<br />&bull; cis-9-octadecenoic acid. &nbsp;&nbsp;(sis, oc-ta-dec-e-no-ik)";aryFADetail[6]="<b>Linoleic Acid</b><br /><br />&bull; 18:2<br />&bull; PolyUnsaturated<br />&bull; cis, cis-9,12-octadecadienoic acid.<br /> (sis, oc-ta-dec-a-di-e-no-ic)";aryFADetail[7]="<b>Linolenic Acid</b><br /><br />&bull; 18:3<br />&bull; PolyUnsaturated<br />&bull; cis, cis,cis-9,12,15-octadecatrienoic acid.<br />(sis, oc-ta-dec-a-tri-e-no-ic)";
function writeHelp(b){var a=document.getElementById("divHelpMsg");switch(b){case 0:a.innerHTML="<p>SoapCalc is a calculator for making your own bath soap at home.</p><p>There are many links on this site to help you learn how to make soap, just click <a href='../info/GettingStarted.asp' target='_blank'>Getting Started</a></p><p>SoapCalc is easy to use with <a href='../info/helptext.asp' target='_blank'>SoapCalc Directions</a>.</p><p>Click the blue number buttons for popups containing information about each section.&nbsp; Longer sections are scrollable.</p>";
break;case 1:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p>Choose what kind of lye you will be using.  <ul><li>Sodium hydroxide, <strong>NaOH</strong>, is used to make soap bars. &nbsp;If you want to make bar soap, click the circle next to NaOH.</li><br /><li>Potassium hyroxide, <strong>KOH</strong>, is used to make liquid soap. &nbsp;This is a more complicated process than making bar soap.&nbsp; It involves adding the water in two stages: one for the soap cooking stage, the other for diluting the soap.&nbsp; You can find more about it <a href='http://candleandsoap.about.com/od/liquidsoap/ss/basicliquidsoap.htm' target='_blank'>here</a>. &nbsp;When making liquid soap, click the circle next to KOH.&nbsp; If you have 90% pure KOH check the 90% box.</li></ul></p>";
break;case 2:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p>This value is the total weight of all the oils that will be used in your recipe. &nbsp;You can use either pounds, ounces or grams as your unit of measurement.</p><p>No matter what unit of measurement you use to create your recipe, the calculated values are displayed in pounds, ounces and grams after clicking the 'View/Print Recipe' button.</p>";break;case 3:a.innerHTML="<span style='color:#404040;'><strong>Help # "+
b+"</strong></span><p><strong>'Water as % of Oils</strong>' is the simplest way to determine the amount of water used in your recipe. &nbsp;It is recommended that beginners use this method and use the default value of 38%.</p><p>More experienced users typically reduce this percentage to around 32-33%.</p><p>Example: Using the default 38% and the total weight of the oils in your recipe is 1 pound, the amount of water in which the lye is mixed would be 0.38 pounds.  The water and lye amounts are calculated on the 'View Recipe' page.</p><p>'<strong>Lye Concentration</strong>' - Advanced users can set the Lye percentage of the water & lye solution directly.&nbsp; Example:  If you want lye to be 34% of (lye + water), click 'Lye Concentration' and enter 34  in the text box to the right of the check box before clicking 'Calculate Recipe'.<p>'<strong>Water : Lye Ratio</strong>' - Advanced users can also set the Water:Lye ratio directly.&nbsp; Example:  If you want the water to lye ratio to be 2 to 1, click 'Water : Lye Ratio' and enter 2:1 before clicking 'Calculate Recipe'.</p>";
break;case 4:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p><strong>Super Fat.</strong>&nbsp; Due to several possible oil variables it is safer to use less lye than needed to saponify the oils in your recipe.&nbsp; This is called a <strong>lye discount</strong> and 5% is generally considered a safe number to use.</p><p>Because discounting the lye by 5% leaves 5% of unsaponified oils in your soap bar this number is also referred to as <strong>super fat</strong>.&nbsp; That extra 5% of superfat not only is a safety factor, it also gives the soap bar extra skin conditioning qualities because approximately 95% of the bar is soap and approximately 5% of the bar is an oil mixture that is deposited on the skin. &nbsp;For more info see <a href='../info/FAQ.asp' target='_blank'>FAQ Number 7</a></p><p><strong>Fragrance.</strong>&nbsp; The amount of fragrance to use is typically about 3-4% of the total weight of the oils used in your recipe.&nbsp; This is commonly specified as ounces per pound of oils or grams per kilogram of oils.&nbsp;  Some suppliers will specify a usage rate for each of their oils.</p><p>Example: The supplier suggests a usage rate .6 oz/lb: 0.6/16 oz = .0375 = 3.75%.  The metric equivalent would be .0375 x 1000 = 37.5 g/kg.  Essential Oils are stronger and usually require a lower percentage than Fragrance Oils.</p>";
break;case 5:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p>When one oil is selected from the list (Oils, Fats and Waxes) the values in the 'One' column will change and be specific for the selected oil.&nbsp; The SAP values will change and the name of the oil will be highlighted or displayed under 'Oils, Fats and Waxes'.&nbsp; Go ahead, select an oil to see the change.</p><p>After you have entered the oils for your recipe and 'Calculate Recipe' is clicked the righthand 'All' column displays the values for your recipe.&nbsp; The next Help #6 explains how to add an oil to the recipe list.</p><p>There are 7 Soap Qualities and 8 Fatty Acids listed.<ul><span><strong>To Pop up more...</strong></span><li>PC - mouse over the word.</li><li>Tablet - tap the word.</ul><ul><span><strong>To close the pop up:</strong></span><li>iPad  - tap any text box just to the right of the words.</li><li>Android - Tap the popup to close it OR tap any text box just to the right of the words.</li></ul><p>At the bottom of this column the ratio of saturated to unsaturated fats is displayed after clicking 'Calculate Recipe'.&nbsp; A typical ratio would be around 40:60 although there are many exceptions to this guideline.</p><p>To learn more about fatty acids in general, click on the 'Fatty Acids' link to Wikipedia at the top of this section.</p><p>To go to the Wikipedia page for a specific fatty acid click on the 'i' button to the right of its name.</p>";
break;case 6:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p>To add an oil to your recipe:<br /><ul><li><strong>PC</strong> - select it from the list in the middle and <span style='color:#F00'>double click it</span> or click the '<span style='color:#F00;font-weight:bold;font-size:16px'>+</span>' in the 'Soap Recipe' section just to the right of the oil list.</li><li><br /><strong>Tablets</strong> - press the selection box just under 'Oils, Fats and Waxes', make the oil selection, then press the 'Add' button just below <strong>'Recipe Oil List'</strong>' OR press the '<span style='color:#F00;font-weight:bold;font-size:16px'>+</span>' sign by the appropriate oil number.</li></ul>To remove an oil from your recipe:<br /><ul><li><strong>PC or Tablets</strong> - click the '<span style='color:#F00;font-weight:bold;font-size:18px'>-</span>' next to the oil you want to remove OR Enter the recipe number (1-14) in the text box next to the button 'Remove #', then press the Remove button.</li></ul></p>";
break;case 7:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p><strong>'Calculate Recipe'</strong> will compute your recipe.&nbsp; SoapCalc will  pop up friendly reminders if there have been any typos or if any information is invalid or missing.</p><p>After clicking <strong>'Calculate Recipe'</strong>, then click <strong>'View/Print Recipe'</strong> to open a new tab in your browser to view or print the recipe details including lye and water amounts.</p><p><strong>Converting weight recipes to percent.</strong><ol><li>Click the round weight button (oz, lb or g) at the top of the right column in the Recipe section.</li><li>Enter the oils and weights.</li><li>Fill in other necessary values and click 'Calculate Recipe'.&nbsp; Perentages will display in the  % column.</li><li>Click the round '%' button,  select the recipe number, then click 'Save Recipe'.</li><li>You can now set your own total oil weight for this recipe.</li></ol><br /><strong>'Reset Recipe'</strong> will clear SoapCalc and reset SoapCalc to default values.</p><p>Checking the '<strong>Multiple tabs</strong>' box will open a new View Recipe tab each time you click 'View/Print Recipe'.</p><p>Checking the '<strong>Bold</strong>' box will display bold ingredient values in the View Recipe tab.</p><p><strong>Note</strong>: By design, some buttons are grayed out (disabled) until 'Calculate Recipe' has been clicked.</p>";
break;case 8:a.innerHTML="<span style='color:#404040;'><strong>Help # "+b+"</strong></span><p>After clicking 'Calculate Recipe', your recipe can be saved using the 'Save Recipe' button.  Up to 8 recipes can be saved as cookies on your device - choose one of the recipe names in the drop down menu before clicking 'Save Recipe'. (Sorry, the recipe names can not be changed.)</p><p>Recipes will be saved using percentages if the round '%' button is selected; or in weights if the round weight button is selected.</p><p><strong>Note</strong>: By design, some buttons are grayed out (disabled) until 'Calculate Recipe' has been clicked.</p>";
break;default:a.innerHTML="<br /><br />No help available."}}
function twOnClick(){!0===document.getElementById("oilWeight0").checked&&(unit="lb",document.getElementById("FragranceRatioUnit").innerHTML="oz/lb",document.getElementById("txtFragranceRatio").value="0.5",document.getElementById("TWunit").innerHTML="lb",document.getElementById("txtTW").value="1",document.getElementById("lblWT").innerHTML="lb",document.getElementById("lbloilWeight0").innerHTML="<strong>Pounds</strong>",document.getElementById("lbloilWeight1").innerHTML="Ounces",document.getElementById("lbloilWeight2").innerHTML=
"Grams");!0===document.getElementById("oilWeight1").checked&&(unit="oz",document.getElementById("FragranceRatioUnit").innerHTML="oz/lb",document.getElementById("txtFragranceRatio").value="0.5",document.getElementById("TWunit").innerHTML="oz",document.getElementById("txtTW").value="16",document.getElementById("lblWT").innerHTML="oz",document.getElementById("lbloilWeight0").innerHTML="Pounds",document.getElementById("lbloilWeight1").innerHTML="<strong>Ounces</strong>",document.getElementById("lbloilWeight2").innerHTML=
"Grams");!0===document.getElementById("oilWeight2").checked&&(unit="g",document.getElementById("FragranceRatioUnit").innerHTML="g/kg",document.getElementById("txtFragranceRatio").value="31",document.getElementById("TWunit").innerHTML="g",document.getElementById("txtTW").value="500",document.getElementById("lblWT").innerHTML="g",document.getElementById("lbloilWeight0").innerHTML="Pounds",document.getElementById("lbloilWeight1").innerHTML="Ounces",document.getElementById("lbloilWeight2").innerHTML=
"<strong>Grams</strong>");document.getElementById("txtTW").focus();document.getElementById("spnFragranceRequired").value=""}
function selOilOnChange(){resetProps();var b=document.getElementById("selOil").selectedIndex;getProperties(b,1);b=parseFloat(aryAllOils[b].sap);document.getElementById("spnHard").value=" "+Hard;document.getElementById("spnCleansing").value=" "+Cleansing;document.getElementById("spnConditioning").value=" "+Conditioning;document.getElementById("spnBubbly").value=" "+Bubbly;document.getElementById("spnCreamy").value=" "+Creamy;document.getElementById("spnIodine").value=" "+Iodine;document.getElementById("spnINS").value=
" "+INS;document.getElementById("spnLauric").value=" "+roundNumber(Lauric,0);document.getElementById("spnLinoleic").value=" "+roundNumber(Linoleic,0);document.getElementById("spnLinolenic").value=" "+roundNumber(Linolenic,0);document.getElementById("spnMyristic").value=" "+roundNumber(Myristic,0);document.getElementById("spnOleic").value=" "+roundNumber(Oleic,0);document.getElementById("spnPalmitic").value=" "+roundNumber(Palmitic,0);document.getElementById("spnRicinoleic").value=" "+roundNumber(Ricinoleic,
0);document.getElementById("spnStearic").value=" "+roundNumber(Stearic,0);document.getElementById("txtSAPKOH").value=b;document.getElementById("txtSAPNaOH").value=roundNumber(40/56.1*b,3)}
function resetAllArraysAndHdnVals(){for(var b=0;14>b;b++)document.getElementById("hdnValue"+b).value="-1",document.getElementById("hdnSap"+b).value="-1",document.getElementById("hdnIndex"+b).value="-1",ary14RecipeWeightVals[b]=0,ary14RecipeSapVals[b]=0,ary14RecipeSelIndexes[b]=0,ary14RecipePercentVals[b]=0,ary14SelectedOilIds[b]=-1}function resetPCandWTArrays(){for(var b=0;14>b;b++)ary14RecipeWeightVals[b]=0,ary14RecipePercentVals[b]=0}
function clearAll(b){if(!b||window.confirm("This will clear all values in the calculator and set it to its default state.\n\nClick OK or press the Enter key to do this.")){textChanged();for(b=0;14>b;b++)removeOil(b);resetProps();resetAllArraysAndHdnVals();document.getElementById("spnHard2").value=" ";document.getElementById("spnCleansing2").value=" ";document.getElementById("spnConditioning2").value=" ";document.getElementById("spnBubbly2").value=" ";document.getElementById("spnCreamy2").value=" ";
document.getElementById("spnIodine2").value=" ";document.getElementById("spnINS2").value=" ";document.getElementById("spnLauric2").value=" ";document.getElementById("spnLinoleic2").value=" ";document.getElementById("spnLinolenic2").value=" ";document.getElementById("spnMyristic2").value=" ";document.getElementById("spnOleic2").value=" ";document.getElementById("spnPalmitic2").value=" ";document.getElementById("spnRicinoleic2").value=" ";document.getElementById("spnStearic2").value=" ";document.getElementById("tdSatRatioMain").value=
" ";document.getElementById("hdnHard2").value="-1";document.getElementById("hdnCleansing2").value="-1";document.getElementById("hdnConditioning2").value="-1";document.getElementById("hdnBubbly2").value="-1";document.getElementById("hdnCreamy2").value="-1";document.getElementById("hdnIodine2").value="-1";document.getElementById("hdnINS2").value="-1";document.getElementById("hdnLauric2").value="-1";document.getElementById("hdnMyristic2").value="-1";document.getElementById("hdnPalmitic2").value="-1";
document.getElementById("hdnStearic2").value="-1";document.getElementById("hdnRicinoleic2").value="-1";document.getElementById("hdnOleic2").value="-1";document.getElementById("hdnLinoleic2").value="-1";document.getElementById("hdnLinolenic2").value="-1";document.getElementById("hydroxide0").checked=!0;document.getElementById("oilWeight0").checked=!0;document.getElementById("waterAmount0").checked=!0;document.getElementById("lblWT").innerHTML="oz";document.getElementById("txtTW").value="1";setWaterPercent(!1);
document.getElementById("chkHowToPrint").checked=!1;document.getElementById("chkBold").checked=!1;document.getElementById("spnLyeConc").value="";document.getElementById("spnWaterLyeRatio").value="";document.getElementById("txtDiscount").value="5";document.getElementById("selOil").selectedIndex=0;document.getElementById("txtFragranceRatio").value="";document.getElementById("FragranceRatioUnit").innerHTML="oz/lb";document.getElementById("txtTotalPerCent").value="";document.getElementById("txtTotalRecipeWeight").value=
"";document.getElementById("spnFragranceRequired").value=""}}
function addOil(b){for(var a=document.getElementById("selOil"),c=a.options[a.selectedIndex].text,d=parseInt(a.options[a.selectedIndex].id.substr(2),10),g=0;14>g;g++)if(ary14SelectedOilIds[g]===d){alert(c+" is already on the list.");return}ary14SelectedOilIds[b]=d;document.getElementById("txtOil"+(b+1)).value=c;document.getElementById("hdnIndex"+b).value=a.selectedIndex;document.getElementById("hdnSap"+b).value=a.options[a.selectedIndex].value;ary14RecipeSelIndexes[b]=parseInt(a.selectedIndex,10);
ary14RecipeSapVals[b]=parseFloat(a.options[a.selectedIndex].value);textChanged()}function autoAddOil(){for(var b=0;14>b;b++)if(0===document.getElementById("txtOil"+(b+1)).value.length){addOil(b);break}}
function removeOil(b){document.getElementById("hdnIndex"+b).value="-1";document.getElementById("txtOil"+(b+1)).value="";document.getElementById("hdnSap"+b).value="-1";ary14RecipeSelIndexes[b]=0;ary14RecipeSapVals[b]=0;ary14SelectedOilIds[b]=-1;document.getElementById("hdnValue"+b).value="-1";document.getElementById("txtPerCent"+(b+1)).value="";document.getElementById("txtWeight"+(b+1)).value="";textChanged()}
function removeOilTablet(){var b;b=document.getElementById("txtRemoveItem").value;if(1==isWhitespace(b))return alert("No item to remove."),!1;b=parseInt(b,10);if(isNaN(b))return alert("Item to be removed must be a number."),!1;if(14<b||1>b)return alert("Item to be removed must be 1 to 14"),!1;removeOil(b-1);document.getElementById("txtRemoveItem").value=""}
function getProperties(b,a){var c;c=parseInt(aryAllOils[b].id,10);31==c||65==c||138==c||40==c||5==c||140==c||142==c||145==c||149==c||101==c?31===c?(Conditioning+=98*a,Creamy+=2*a,Hard+=2*a,INS+=77*a,Iodine+=92*a,PolyUnsaturated+=100*a):65===c?(Hard+=100*a,Cleansing+=100*a,Bubbly+=100*a,Lauric+=2*a,Myristic+=1*a,INS+=324*a,Iodine+=1*a,Saturated+=90*a):138==c?(Hard+=7*a,Creamy+=6*a,Conditioning+=93*a,Oleic+=14*a,Linoleic+=11*a,Linolenic+=9*a,INS+=67*a,Iodine+=105*a,Saturated+=6*a,MonoUnsaturated+=70*
a,PolyUnsaturated+=24*a):40===c?(Hard+=5*a,Creamy+=1*a,Conditioning+=95*a,Oleic+=17*a,Linoleic+=13*a,Linolenic+=9*a,INS+=69*a,Iodine+=106*a,Saturated+=7*a,MonoUnsaturated+=68*a,PolyUnsaturated+=25*a):5===c?(Hard+=90*a,Creamy+=50*a,Conditioning+=50*a,INS+=84*a,Iodine+=10*a):140===c?(Hard+=28*a,Creamy+=3*a,Conditioning+=72*a,Myristic+=5*a,Palmitic+=19*a,Stearic+=2*a,Oleic+=23*a,Linoleic+=2*a,Linolenic+=1*a,INS+=69*a,Iodine+=106*a,Saturated+=28*a,MonoUnsaturated+=32*a,PolyUnsaturated+=40*a):142===c?
(Hard+=68*a,Creamy+=60*a,Conditioning=60*a,INS+=12*a,Iodine+=106*a):145===c?(Hard+=6*a,Creamy+=80*a,Conditioning+=94*a,Palmitic+=3*a,Stearic+=2*a,Oleic+=18*a,Linoleic+=11*a,Linolenic+=4*a,INS+=70*a,Iodine+=98*a):149==c?(Hard+=6*a,Cleansing+=2*a,Creamy+=4*a,Bubbly+=2*a,Conditioning+=83*a,Lauric+=1*a,Myristic+=1*a,Palmitic+=2*a,Stearic+=2*a,Oleic+=44*a,Linoleic+=2*a,Linolenic+=2*a,INS+=107*a,Iodine+=68*a,Saturated+=54*a,MonoUnsaturated+=42*a,PolyUnsaturated+=2*a):101==c&&(Hard+=54*a,Creamy+=43*a,Conditioning+=
44*a,Palmitic+=8*a,Stearic+=35*a,Oleic+=42*a,Linoleic+=2*a,INS+=153*a,Iodine+=39*a,Saturated+=54*a,MonoUnsaturated+=42*a,PolyUnsaturated+=2*a):(c=parseInt(aryAllOils[b].lauric,10),0<c&&(Hard+=c*a,Cleansing+=c*a,Bubbly+=c*a,Lauric+=c*a,Saturated+=c*a),c=parseInt(aryAllOils[b].myristic,10),0<c&&(Hard+=c*a,Cleansing+=c*a,Bubbly+=c*a,Myristic+=c*a,Saturated+=c*a),c=parseInt(aryAllOils[b].palmitic,10),0<c&&(Hard+=c*a,Creamy+=c*a,Palmitic+=c*a,Saturated+=c*a),c=parseInt(aryAllOils[b].stearic,10),0<c&&(Hard+=
c*a,Creamy+=c*a,Stearic+=c*a,Saturated+=c*a),c=parseInt(aryAllOils[b].ricinoleic,10),0<c&&(Conditioning+=c*a,Bubbly+=c*a,Creamy+=c*a,Ricinoleic+=c*a,MonoUnsaturated+=c*a),c=parseInt(aryAllOils[b].oleic,10),0<c&&(Conditioning+=c*a,Oleic+=c*a,MonoUnsaturated+=c*a),c=parseInt(aryAllOils[b].linoleic,10),0<c&&(Conditioning+=c*a,Linoleic+=c*a,PolyUnsaturated+=c*a),c=parseInt(aryAllOils[b].linolenic,10),0<c&&(Conditioning+=c*a,Linolenic+=c*a,PolyUnsaturated+=c*a),INS+=aryAllOils[b].ins*a,Iodine+=aryAllOils[b].iodine*
a)}function resetProps(){PolyUnsaturated=MonoUnsaturated=Saturated=Stearic=Ricinoleic=Palmitic=Oleic=Myristic=Linolenic=Linoleic=Lauric=INS=Iodine=Creamy=Conditioning=Bubbly=Cleansing=Hard=0}
function validate(){var b=document.getElementById("txtTW").value,a=document.getElementById("radPercent0"),c,d,g;for(c=1;14>=c;c++)d+=document.getElementById("txtOil"+c).value;if(0===d.length)return window.alert("Please add at least one oil or fat to your recipe.\n\nClick help button 6 for instructions on how to add or remove an oil."),!1;g=0;if(!0===a.checked){if(0===b.length)return window.alert("Please fill in Total Oil Weight."),!1;if(isNaN(b))return window.alert("Total Oil Weight is not a number."),
!1;c=parseFloat(b);if(0>=c)return window.alert("Total Oil Weight can not be less than 0 (zero)."),!1;for(c=1;14>=c;c++)if(d=document.getElementById("txtOil"+c).value,b=document.getElementById("txtPerCent"+c).value,!isEmpty(d)){if(isEmpty(b))return window.alert("Please enter a value for Oil Number "+c+", "+d+", or remove it from the recipe."),!1;d=parseFloat(b);if(isNaN(d))return window.alert("Value for Oil Number "+c+" is not a number"),!1;if(0>=parseFloat(b))return window.alert("Percent value for Oil Number "+
c+" can not be zero or less. Either remove oil or put in a number greater than zero."),!1;g+=d}else if(!isEmpty(b))return window.alert("There is no oil name listed for Oil Number "+c+"  but the percentage column contains a value.\n\nPlease either add an oil for number "+c+" or click the minus sign next to item "+c+" to remove the percentage."),!1;c=roundNumber(g,1);document.getElementById("txtTotalPerCent").value=c;if(100!=c)return c=roundNumber(100-c,4),document.getElementById("txtTotalPerCent").style.color=
"#FF0000",window.alert("Total Per Cent does not equal 100%\n\nAdjust by"+(0<c?" adding ":" taking away ")+Math.abs(c)+" %"),!1;document.getElementById("txtTotalPerCent").style.color="#000000"}else for(g=0,c=1;14>=c;c++)if(b=document.getElementById("txtWeight"+c).value,d=document.getElementById("txtOil"+c).value,!isEmpty(d)){if(isEmpty(b))return window.alert("There is no weight value for Oil Number "+c+".  \n\nEither add a weight value for Oil Number "+c+" or click the minus sign next to item "+c+
" to remove it."),!1;if(isNaN(b)&&0<b.length)return window.alert("Weight value for Oil Number "+c+" is not a number"),!1;if(0>=parseFloat(b))return window.alert("Weight value for Oil Number "+c+" can not be zero or less. Either remove oil or put in a number greater than zero."),!1;g+=parseFloat(b)}else if(!isEmpty(b))return window.alert("There is no oil name listed for Oil Number "+c+"  but the weight column contains a value.\n\nPlease either add an oil for number "+c+" or click the minus sign next to item "+
c+" to remove the weight."),!1;if(!1===document.getElementById("waterAmount1").checked&&!1===document.getElementById("waterAmount2").checked&&(c=document.getElementById("txtWaterPercent").value,isWhitespace(c)||isNaN(c)))return window.alert('"Water as % of Oils" is not a number.'),!1;c=document.getElementById("txtDiscount").value;if(isWhitespace(c)||isNaN(c))document.getElementById("txtDiscount").value="0";c=document.getElementById("txtFragranceRatio").value;if(0!==c.length){if(isNaN(c))return window.alert("Fragrance ratio is not a number"),
!1;parseFloat(c)}if(!0===FixedConc&&(c=document.getElementById("spnLyeConc").value,isNaN(parseFloat(c))))return window.alert("Lye Concentration value must be a number.\nEither uncheck the Lye Concentration 'Set' box or enter a number."),!1;if(!0===FixedRatio){c=document.getElementById("spnWaterLyeRatio").value;if(-1==c.indexOf(":"))return window.alert("The ratio must be expressed as 'Water:Lye'.\nA colon, : , must be be between the water value and the lye value."),!1;c=c.split(":");if(isNaN(c[0])||
isNaN(c[1]))return window.alert("Water and Lye values in the ratio must both be numbers."),!1}return!0}
function ComputeUsingPC(){var b,a,c,d,g,f;c=g=0;d=parseFloat(document.getElementById("txtTW").value);for(var e=1;14>=e;e++)b=parseFloat(document.getElementById("txtPerCent"+e).value),isNaN(b)&&(b=0),ary14RecipePercentVals[e-1]=b/100,g+=b,a=b*d/100,0<b&&(document.getElementById("txtWeight"+e).value=fixPCrounding(a)),ary14RecipeWeightVals[e-1]=a,c+=a,b=document.getElementById("txtOil"+e),f=document.getElementById("txtWeight"+e),f.value=""===b.value?"":a;document.getElementById("txtTotalPerCent").value=
roundNumber(g,4);document.getElementById("txtTotalRecipeWeight").value=roundNumber(c,3)}
function ComputeUsingWT(){for(var b,a=0,c=0,d=1;14>=d;d++)b=document.getElementById("txtWeight"+d).value,0<b.length?(ary14RecipeWeightVals[d-1]=parseFloat(b),c+=ary14RecipeWeightVals[d-1]):ary14RecipeWeightVals[d-1]=0;for(d=1;14>=d;d++)ary14RecipePercentVals[d-1]=roundNumber(ary14RecipeWeightVals[d-1]/c*100,2),b=document.getElementById("txtPerCent"+d),0===ary14RecipePercentVals[d-1]?b.value="":(b.value=fixPCrounding(ary14RecipePercentVals[d-1]),a+=ary14RecipePercentVals[d-1]);document.getElementById("txtTotalPerCent").value=
roundNumber(a,4);document.getElementById("txtTotalRecipeWeight").value=roundNumber(c,3);document.getElementById("txtTW").value=roundNumber(c,3)}
function computeRecipe(b){var a,c;resetPCandWTArrays();resetProps();if(validate()){!0===document.getElementById("radPercent0").checked?ComputeUsingPC():ComputeUsingWT();for(b=g_tot=0;b<ary14RecipeWeightVals.length;b++)0!==ary14RecipeWeightVals[b]&&(g_tot+=ary14RecipeWeightVals[b]);for(b=1;14>=b;b++)a=document.getElementById("txtOil"+b).value,0<a.length&&(a=ary14RecipeSelIndexes[b-1],c=ary14RecipeWeightVals[b-1]/g_tot,getProperties(a,c));document.getElementById("spnHard2").value=" "+roundNumber(Hard,
0);document.getElementById("spnCleansing2").value=" "+roundNumber(Cleansing,0);document.getElementById("spnConditioning2").value=" "+roundNumber(Conditioning,0);document.getElementById("spnBubbly2").value=" "+roundNumber(Bubbly,0);document.getElementById("spnCreamy2").value=" "+roundNumber(Creamy,0);document.getElementById("spnIodine2").value=" "+roundNumber(Iodine,0);document.getElementById("spnINS2").value=" "+roundNumber(INS,0);document.getElementById("spnLauric2").value=" "+roundNumber(Lauric,
0);document.getElementById("spnLinoleic2").value=" "+roundNumber(Linoleic,0);document.getElementById("spnLinolenic2").value=" "+roundNumber(Linolenic,0);document.getElementById("spnMyristic2").value=" "+roundNumber(Myristic,0);document.getElementById("spnOleic2").value=" "+roundNumber(Oleic,0);document.getElementById("spnPalmitic2").value=" "+roundNumber(Palmitic,0);document.getElementById("spnRicinoleic2").value=" "+roundNumber(Ricinoleic,0);document.getElementById("spnStearic2").value=" "+roundNumber(Stearic,
0);b=0===document.getElementById("txtFragranceRatio").value.length?0:parseFloat(document.getElementById("txtFragranceRatio").value);!0===document.getElementById("oilWeight0").checked&&(document.getElementById("spnFragranceRequired").value=" "+roundNumber(b*g_tot,3)+" Oz");!0===document.getElementById("oilWeight1").checked&&(a=g_tot/16,document.getElementById("spnFragranceRequired").value=" "+roundNumber(b*a,3)+" Oz");!0===document.getElementById("oilWeight2").checked&&(document.getElementById("spnFragranceRequired").value=
" "+roundNumber(b*g_tot/1E3,2)+" g");showSatRatio(roundNumber(Saturated,0),roundNumber(MonoUnsaturated,0),roundNumber(PolyUnsaturated,0));g_Computed=!0;setButtons(!0)}}function textChanged(){g_Computed=!1;setButtons(!1)}
function printRecipe(){var b,a,c;for(a=1;14>=a;a++)b=document.getElementById("txtOil"+a).value,0<b.length&&(c=ary14RecipeSelIndexes[a-1],b=ary14RecipeWeightVals[a-1]/g_tot,getProperties(c,b),!0===document.getElementById("radPercent0").checked?document.getElementById("hdnValue"+(a-1)).value=b:document.getElementById("hdnValue"+(a-1)).value=ary14RecipeWeightVals[a-1]);document.getElementById("hdnHard2").value=document.getElementById("spnHard2").value;document.getElementById("hdnCleansing2").value=document.getElementById("spnCleansing2").value;
document.getElementById("hdnConditioning2").value=document.getElementById("spnConditioning2").value;document.getElementById("hdnBubbly2").value=document.getElementById("spnBubbly2").value;document.getElementById("hdnCreamy2").value=document.getElementById("spnCreamy2").value;document.getElementById("hdnIodine2").value=document.getElementById("spnIodine2").value;document.getElementById("hdnINS2").value=document.getElementById("spnINS2").value;document.getElementById("hdnLauric2").value=document.getElementById("spnLauric2").value;
document.getElementById("hdnMyristic2").value=document.getElementById("spnMyristic2").value;document.getElementById("hdnPalmitic2").value=document.getElementById("spnPalmitic2").value;document.getElementById("hdnStearic2").value=document.getElementById("spnStearic2").value;document.getElementById("hdnRicinoleic2").value=document.getElementById("spnRicinoleic2").value;document.getElementById("hdnOleic2").value=document.getElementById("spnOleic2").value;document.getElementById("hdnLinoleic2").value=
document.getElementById("spnLinoleic2").value;document.getElementById("hdnLinolenic2").value=document.getElementById("spnLinolenic2").value;!0===g_Computed&&(document.getElementById("chkHowToPrint").checked?document.getElementById("recipeData").target="_blank":document.getElementById("recipeData").target="printWin",document.forms.recipeData.submit())}
function setButtons(b){b?(document.getElementById("btnViewRecipe").disabled=!1,document.getElementById("btnSaveRecipe").disabled=!1,document.getElementById("btnViewRecipe").style.cursor="pointer",document.getElementById("btnSaveRecipe").style.cursor="pointer"):(document.getElementById("btnViewRecipe").disabled=!0,document.getElementById("btnSaveRecipe").disabled=!0,document.getElementById("btnViewRecipe").style.cursor="default",document.getElementById("btnSaveRecipe").style.cursor="default")}
function setWaterPercent(b){var a=document.getElementById("txtWaterPercent"),c=document.getElementById("spnLyeConc"),d=document.getElementById("spnWaterLyeRatio");FixedRatio=FixedConc=!1;a.value="38";a.style.backgroundColor="#C9FCD0";a.readOnly=!1;document.getElementById("lblwaterAmount0").style.fontWeight="900";c.style.backgroundColor="#FFFFFF";c.value="";c.readOnly=!0;document.getElementById("lblwaterAmount1").style.fontWeight="400";d.style.backgroundColor="#FFFFFF";d.value="";d.readOnly=!0;d.style.backgroundColor=
"#FFFFFF";document.getElementById("lblwaterAmount2").style.fontWeight="400";b&&a.focus()}
function setLyeConcentration(b){var a=document.getElementById("txtWaterPercent"),c=document.getElementById("spnLyeConc"),d=document.getElementById("spnWaterLyeRatio");FixedConc=!0;FixedRatio=!1;c.style.backgroundColor="#C9FCD0";c.readOnly=!1;document.getElementById("lblwaterAmount1").style.fontWeight="900";a.style.backgroundColor="#FFFFFF";a.value="";a.readOnly=!0;document.getElementById("lblwaterAmount0").style.fontWeight="400";d.style.backgroundColor="#FFFFFF";d.value="";d.readOnly=!0;document.getElementById("lblwaterAmount2").style.fontWeight=
"400";b&&c.focus()}
function setWaterLyeRatio(b){var a=document.getElementById("txtWaterPercent"),c=document.getElementById("spnLyeConc"),d=document.getElementById("spnWaterLyeRatio");FixedConc=!1;FixedRatio=!0;d.style.backgroundColor="#C9FCD0";d.readOnly=!1;document.getElementById("lblwaterAmount2").style.fontWeight="900";a.style.backgroundColor="#FFFFFF";a.value="";a.readOnly=!0;document.getElementById("lblwaterAmount0").style.fontWeight="400";c.style.backgroundColor="#FFFFFF";c.value="";c.readOnly=!0;document.getElementById("lblwaterAmount1").style.fontWeight=
"400";a.value="";c.value="";b&&d.focus()}function setFixedWaterMethod(){for(var b,a=document.getElementsByName("R4"),c=0;c<a.length;c++)1==a[c].checked&&(b=parseInt(a[c].value,10));g_FixedRatio=g_FixedConc=!1;switch(b){case 0:setWaterPercent(!0);break;case 1:setLyeConcentration(!0);break;case 2:setWaterLyeRatio(!0)}}
function PorWClick(){var b;g_Computed=!1;setButtons(!1);if(!0===document.getElementById("radPercent1").checked){document.getElementById("hdnPorW").value="1";for(b=1;14>=b;b++)document.getElementById("txtPerCent"+b).style.backgroundColor="#FFFFFF",document.getElementById("txtPerCent"+b).readOnly=!0,document.getElementById("txtWeight"+b).readOnly=!1,document.getElementById("txtWeight"+b).style.backgroundColor="#C9FCD0";document.getElementById("radPercent0").checked=!1;document.getElementById("radPercent1").checked=
!0;document.getElementById("txtTW").style.backgroundColor="#FFFFFF";document.getElementById("txtTW").readOnly=!0}else{document.getElementById("hdnPorW").value="0";for(b=1;14>=b;b++)document.getElementById("txtPerCent"+b).style.backgroundColor="#C9FCD0",document.getElementById("txtPerCent"+b).readOnly=!1,document.getElementById("txtWeight"+b).style.backgroundColor="#FFFFFF",document.getElementById("txtWeight"+b).readOnly=!0,document.getElementById("txtWeight"+b).style.backgroundColor="#FFFFFF";document.getElementById("radPercent0").checked=
!0;document.getElementById("radPercent1").checked=!1;document.getElementById("txtTW").style.backgroundColor="#C9FCD0";document.getElementById("txtTW").readOnly=!1}}
function hydroxideChange(b){null==b&&(b=document.getElementsByName("R2")[0].checked?document.getElementById("hydroxide0"):document.getElementById("hydroxide1"));1==b.value?(document.getElementById("lblNaOH").innerHTML="&nbsp;NaOH",document.getElementById("lblKOH").innerHTML="<strong>&nbsp;KOH</strong>",document.getElementById("chkNintyPerCent").disabled=!1):(document.getElementById("lblNaOH").innerHTML="<strong>&nbsp;NaOH</strong>",document.getElementById("lblKOH").innerHTML="&nbsp;KOH",document.getElementById("chkNintyPerCent").disabled=
!0,document.getElementById("chkNintyPerCent").checked=!1);g_Computed=!1}function kohPurityChanged(){g_90PercentKOH=!0===document.getElementById("chkNintyPerCent").checked?!0:!1;textChanged()}
function SaveRecipe(){var b,a,c,d,g,f,e=c="";b=new Date;a=b.getTime()+31536E6;b.setTime(a);g=document.getElementById("selRecipeName").value;for(a=1;14>=a;a++)d=!0===document.getElementById("radPercent0").checked?document.getElementById("txtPerCent"+a):document.getElementById("txtWeight"+a),f=document.getElementById("hdnIndex"+(a-1)),c=-1!=f.value?14==a?c+(aryAllOils[f.value].id+"^"+d.value+"#"):c+(aryAllOils[f.value].id+"^"+d.value+"@"):14==a?c+(f.value+"^0#"):c+(f.value+"^0@");!0===document.getElementById("oilWeight0").checked&&
(e+="unit^lb@");!0===document.getElementById("oilWeight1").checked&&(e+="unit^oz@");!0===document.getElementById("oilWeight2").checked&&(e+="unit^gm@");e+="wt^"+document.getElementById("txtTW").value+"@";e+="wpc^"+document.getElementById("txtWaterPercent").value+"@";e+="wdis^"+document.getElementById("txtDiscount").value+"@";e+="lyecon^"+document.getElementById("spnLyeConc").value+"@";e+="wlratio^"+document.getElementById("spnWaterLyeRatio").value+"@";e+="chklc^"+document.getElementById("waterAmount1").checked+
"@";e+="chkwl^"+document.getElementById("waterAmount2").checked+"@";e+="pw^"+document.getElementById("radPercent0").checked+"@";e+="wpc^"+document.getElementById("txtWaterPercent").value+"@";e+="wdis^"+document.getElementById("txtDiscount").value+"@";e+="naoh^"+document.getElementById("hydroxide0").checked+"@";e+="frag^"+document.getElementById("txtFragranceRatio").value+"@";e=document.getElementById("chkNintyPerCent").checked?e+"ninty^true":e+"ninty^false";document.cookie=g+"="+(c+e)+";expires="+
b.toGMTString();b=document.getElementById("divRecipeSaved");b.style.display="block";fade(b)}function fade(b){var a=1,c=setInterval(function(){.1>=a&&(clearInterval(c),b.style.display="none");b.style.opacity=a;b.style.filter="alpha(opacity="+100*a+")";a-=.05*a},50)}function GetCookie(b){var a=document.cookie,c=a.indexOf(b);return-1!=c?(b=c+b.length+1,c=a.indexOf(";",b),-1==c&&(c=a.length),a=a.substring(b,c),unescape(a)):""}
function GetRecipe(){var b=document.getElementById("selRecipeName").value,a=[],c=[],d,g,f=GetCookie(b),e=document.getElementById("selOil");g=b.lastIndexOf("e");d=b.substring(0,g+1);g=b.substring(g+1);var b=0,k;clearAll(!1);d+=" "+g;if(0===f.length)window.alert(d+" has not been saved as a cookie on your computer.");else{for(d=1;14>=d;d++)document.getElementById("txtWeight"+d).value="",document.getElementById("txtPerCent"+d).value="";document.getElementById("spnFragranceRequired").value="";document.getElementById("txtTotalPerCent").value=
"";document.getElementById("txtTotalRecipeWeight").value="";d=document.getElementById("txtWaterPercent");g=document.getElementById("spnLyeConc");k=document.getElementById("spnWaterLyeRatio");for(var m=document.getElementById("lblwaterAmount0"),n=document.getElementById("lblwaterAmount1"),p=document.getElementById("lblwaterAmount2"),q=f.split("#"),l=q[0].split("@"),h,r=0,f=0;f<l.length;f++)h=l[f].split("^"),a[f]=h[0],c[f]=h[1],"0"!=h[1]&&(ary14SelectedOilIds[r++]=parseInt(h[0],10));l=q[1].split("@");
for(f=0;f<l.length;f++)switch(h=l[f].split("^"),h[0]){case "unit":"lb"==h[1]&&(document.getElementById("oilWeight0").checked=!0,document.getElementById("lblWT").innerHTML="lb",document.getElementById("TWunit").innerHTML="Pounds",document.getElementById("FragranceRatioUnit").innerHTML="oz/lb",unit="lb");"oz"==h[1]&&(document.getElementById("oilWeight1").checked=!0,document.getElementById("lblWT").innerHTML="oz",document.getElementById("TWunit").innerHTML="Ounces",document.getElementById("FragranceRatioUnit").innerHTML=
"oz/lb",unit="oz");"gm"==h[1]&&(document.getElementById("oilWeight2").checked=!0,document.getElementById("lblWT").innerHTML="g",document.getElementById("TWunit").innerHTML="Grams",document.getElementById("FragranceRatioUnit").innerHTML="g/kg",unit="g");break;case "wt":document.getElementById("txtTW").value=h[1];document.getElementById("txtTotalRecipeWeight").value=h[1];break;case "wpc":document.getElementById("txtWaterPercent").value=h[1];break;case "wdis":document.getElementById("txtDiscount").value=
h[1];break;case "lyecon":document.getElementById("spnLyeConc").value=h[1];break;case "wlratio":document.getElementById("spnWaterLyeRatio").value=h[1];break;case "chklc":"true"==h[1]?(document.forms.recipeData.elements.R4[1].checked=!0,g.style.backgroundColor="#C9FCD0",g.focus(),g.readOnly=!1,n.style.fontWeight="900",d.value="",k.value="",FixedConc=!0):(document.forms.recipeData.elements.R4[1].checked=!1,g.style.backgroundColor="#FFFFFF",g.readOnly=!0,n.style.fontWeight="400",FixedConc=!1);break;case "chkwl":"true"==
h[1]?(document.forms.recipeData.elements.R4[2].checked=!0,k.style.backgroundColor="#C9FCD0",k.focus(),k.readOnly=!1,p.style.fontWeight="900",d.value="",g.value="",FixedRatio=!0):(document.forms.recipeData.elements.R4[2].checked=!1,k.style.backgroundColor="#FFFFFF",k.readOnly=!0,p.style.fontWeight="400",FixedRatio=!1);break;case "pw":"true"==h[1]?(document.getElementById("radPercent0").checked=!0,document.getElementById("txtTW").style.backgroundColor="#C9FCD0"):(document.getElementById("radPercent1").checked=
!0,document.getElementById("txtTW").style.backgroundColor="#FFFFFF");document.getElementById("txtTW").readOnly=!0;break;case "wpc":document.getElementById("txtWaterPercent").value=h[1];break;case "wdis":document.getElementById("txtDiscount").value=h[1];break;case "naoh":hydroxideChange(document.getElementById("hydroxide0"));"true"===h[1]?document.getElementById("hydroxide0").checked=!0:(document.getElementById("hydroxide1").checked=!0,document.getElementById("chkNintyPerCent").disabled=!1);break;
case "frag":document.getElementById("txtFragranceRatio").value=h[1];break;case "ninty":"true"===h[1]?document.getElementById("chkNintyPerCent").checked=!0:document.getElementById("chkNintyPerCent").checked=!1}!1===document.forms.recipeData.elements.R4[1].checked&&!1===document.forms.recipeData.elements.R4[2].checked?(document.forms.recipeData.elements.R4[0].checked=!0,d.style.backgroundColor="#C9FCD0",d.readOnly=!1,m.style.fontWeight="900",g.value="",k.value="",FixedConc=!1):(d.style.backgroundColor=
"#FFFFFF",d.readOnly=!0,m.style.fontWeight="400");for(f=0;f<a.length;f++)if(d=f+1,k=!0===document.getElementById("radPercent0").checked?document.getElementById("txtPerCent"+d):document.getElementById("txtWeight"+d),d=document.getElementById("txtOil"+d),g=document.getElementById("hdnIndex"+f),-1==a[f])d.value="",k.value="",g.value="-1",ary14RecipeSapVals[f]=0,ary14RecipeSelIndexes[f]=0;else{isNaN(c[f])?k.value="":(k.value=c[f],!0===document.getElementById("radPercent0").checked&&(b+=parseFloat(c[f])));
for(k=0;k<aryAllOils.length&&a[f]!=aryAllOils[k].id;k++);d.value=e.options[k].text;ary14RecipeSelIndexes[f]=k;g.value=k;ary14RecipeSapVals[f]=parseFloat(e.options[k].value);document.getElementById("hdnSap"+f).value=e.options[k].value}!0===document.getElementById("radPercent0").checked&&(document.getElementById("txtTotalPerCent").value=b,100!=roundNumber(b,1)?document.getElementById("txtTotalPerCent").style.color="#FF0000":document.getElementById("txtTotalPerCent").style.color="#000000");PorWClick();
setFixedWaterMethod()}}function roundNumber(b,a){return Math.round(b*Math.pow(10,a))/Math.pow(10,a)}function isWhitespace(b){var a;if(isEmpty(b))return!0;for(a=0;a<b.length;a++){var c=b.charAt(a);if(-1==" \t\n\r".indexOf(c))return!1}return!0}function isEmpty(b){return null===b||0===b.length}function fixPCrounding(b){var a;a=b.toString();if(-1==a.indexOf("."))return b;a=a.split(".");b=a[0];a=a[1].slice(0,12);return parseFloat(b+"."+a)}
function hideHelp(){document.getElementById("divOnPageHelp").style.display="none"}
function showHelp(b){b=parseInt((b.id+"").substr(4),10);var a=document.getElementById("divOnPageHelp");a.style.height=0==b?"230px":2==b?"220px":"250px";switch(b){case 0:a.style.top="250px";a.style.left="165px";writeHelp(0);break;case 1:a.style.top="370px";a.style.left="165px";writeHelp(1);break;case 2:a.style.top="370px";a.style.left="165px";writeHelp(2);break;case 3:a.style.top="370px";a.style.left="390px";writeHelp(3);break;case 4:a.style.top="370px";a.style.left="540px";writeHelp(4);break;case 5:a.style.top=
"60px";a.style.left="165px";writeHelp(5);break;case 6:a.style.top="90px";a.style.left="365px";writeHelp(6);break;case 7:a.style.top="525px";a.style.left="365px";writeHelp(7);break;case 8:a.style.top="90px",a.style.left="455px",writeHelp(8)}a.style.display="block";document.getElementById("closeHelp1").style.height=document.getElementById("divHelpMsg").clientHeight+"px";document.getElementById("divOnPageHelp").scrollTop=0}
function closeOnPageHelp(){document.getElementById("divOnPageHelp").style.display="none"}function showCount(){document.getElementById("spnCount").style.display="inline"}function hideCount(){document.getElementById("spnCount").style.display="none"}function showFADetail(b){document.getElementById("divFADetail").innerHTML=aryFADetail[b]+tailFADetail;document.getElementById("divFADetail").style.display="block"}function hideFADetail(){document.getElementById("divFADetail").style.display="none"}
function showRanges(b){document.getElementById("divRanges").innerHTML=aryRanges[b];document.getElementById("divRanges").style.display="block"}function hideRanges(){document.getElementById("divRanges").style.display="none"}function showSatRatio(b,a,c){a+=c;var d=100-(b+a);c=roundNumber(b/(b+a)*d,0);d=roundNumber(a/(b+a)*d,0);b=b+c+" : "+(a+d);document.getElementById("tdSatRatioMain").value=b};
